name=FansElectronics_DMD8266
version=1.0.0
author=Fans Electronics, Irfan Indra Kurniawan, S.T
maintainer=Irfan Indra Kurniawan, S.T <info@fanselectronics.com>
sentence=DMD8266 Library for ESP8266 HUB12 & HUB08 Support P10, P4.75, & P7.62.
paragraph=DMD8266 Library for ESP8266 HUB12 & HUB08 Support P10, P4.75, & P7.62 Single Color. This library is designed to control DMD (Dot Matrix Display) panels using ESP8266 microcontrollers.
category=Display
url=https://github.com/Vean/FansElectronics_DMD8266
architectures=esp8266
license=MIT
includes=FansElectronics_DMD8266.h
